name: act_flutter
description: Independent mobile and desktop studio for AntiCapTrad.
publish_to: none
version: 0.1.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  ores_otel_flutter:
    git:
      url: https://github.com/ores-otel/ores-otel-flutter.git
      ref: c7cf306eee7b07408057753251f937ea58f8e9ed
  flutter:
    sdk: flutter
  shared_auth_flutter:
    git:
      url: https://github.com/shared-auth/shared-auth-flutter.git
      ref: 1977df365220a6fcd19ac74bfebaf5acfbae9ca5

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
